/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ducho' at '9/22/16 1:12 PM' with Gradle 2.10
 *
 * @author ducho, @date 9/22/16 1:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
